/* generated vector source file - do not edit */
#include "bsp_api.h"
/* Do not build these data structures if no interrupts are currently allocated because IAR will have build errors. */
#if VECTOR_DATA_IRQ_COUNT > 0
        BSP_DONT_REMOVE const fsp_vector_t g_vector_table[BSP_ICU_VECTOR_MAX_ENTRIES] BSP_PLACE_IN_SECTION(BSP_SECTION_APPLICATION_VECTORS) =
        {
                        [0] = spi_rxi_isr, /* SPI0 RXI (Receive buffer full) */
            [1] = spi_txi_isr, /* SPI0 TXI (Transmit buffer empty) */
            [2] = spi_tei_isr, /* SPI0 TEI (Transmission complete event) */
            [3] = spi_eri_isr, /* SPI0 ERI (Error) */
            [4] = spi_rxi_isr, /* SPI1 RXI (Receive buffer full) */
            [5] = spi_txi_isr, /* SPI1 TXI (Transmit buffer empty) */
            [6] = spi_tei_isr, /* SPI1 TEI (Transmission complete event) */
            [7] = spi_eri_isr, /* SPI1 ERI (Error) */
            [8] = sci_uart_rxi_isr, /* SCI0 RXI (Receive data full) */
            [9] = sci_uart_txi_isr, /* SCI0 TXI (Transmit data empty) */
            [10] = sci_uart_tei_isr, /* SCI0 TEI (Transmit end) */
            [11] = sci_uart_eri_isr, /* SCI0 ERI (Receive error) */
            [12] = sci_uart_rxi_isr, /* SCI1 RXI (Received data full) */
            [13] = sci_uart_txi_isr, /* SCI1 TXI (Transmit data empty) */
            [14] = sci_uart_tei_isr, /* SCI1 TEI (Transmit end) */
            [15] = sci_uart_eri_isr, /* SCI1 ERI (Receive error) */
            [16] = sci_uart_rxi_isr, /* SCI2 RXI (Received data full) */
            [17] = sci_uart_txi_isr, /* SCI2 TXI (Transmit data empty) */
            [18] = sci_uart_tei_isr, /* SCI2 TEI (Transmit end) */
            [19] = sci_uart_eri_isr, /* SCI2 ERI (Receive error) */
            [20] = sci_uart_rxi_isr, /* SCI3 RXI (Received data full) */
            [21] = sci_uart_txi_isr, /* SCI3 TXI (Transmit data empty) */
            [22] = sci_uart_tei_isr, /* SCI3 TEI (Transmit end) */
            [23] = sci_uart_eri_isr, /* SCI3 ERI (Receive error) */
            [24] = sci_uart_rxi_isr, /* SCI4 RXI (Received data full) */
            [25] = sci_uart_txi_isr, /* SCI4 TXI (Transmit data empty) */
            [26] = sci_uart_tei_isr, /* SCI4 TEI (Transmit end) */
            [27] = sci_uart_eri_isr, /* SCI4 ERI (Receive error) */
            [28] = sci_uart_rxi_isr, /* SCI5 RXI (Received data full) */
            [29] = sci_uart_txi_isr, /* SCI5 TXI (Transmit data empty) */
            [30] = sci_uart_tei_isr, /* SCI5 TEI (Transmit end) */
            [31] = sci_uart_eri_isr, /* SCI5 ERI (Receive error) */
            [32] = sci_uart_rxi_isr, /* SCI6 RXI (Received data full) */
            [33] = sci_uart_txi_isr, /* SCI6 TXI (Transmit data empty) */
            [34] = sci_uart_tei_isr, /* SCI6 TEI (Transmit end) */
            [35] = sci_uart_eri_isr, /* SCI6 ERI (Receive error) */
            [36] = sci_uart_rxi_isr, /* SCI7 RXI (Received data full) */
            [37] = sci_uart_txi_isr, /* SCI7 TXI (Transmit data empty) */
            [38] = sci_uart_tei_isr, /* SCI7 TEI (Transmit end) */
            [39] = sci_uart_eri_isr, /* SCI7 ERI (Receive error) */
            [40] = sci_uart_rxi_isr, /* SCI8 RXI (Received data full) */
            [41] = sci_uart_txi_isr, /* SCI8 TXI (Transmit data empty) */
            [42] = sci_uart_tei_isr, /* SCI8 TEI (Transmit end) */
            [43] = sci_uart_eri_isr, /* SCI8 ERI (Receive error) */
            [44] = sci_uart_rxi_isr, /* SCI9 RXI (Received data full) */
            [45] = sci_uart_txi_isr, /* SCI9 TXI (Transmit data empty) */
            [46] = sci_uart_tei_isr, /* SCI9 TEI (Transmit end) */
            [47] = sci_uart_eri_isr, /* SCI9 ERI (Receive error) */
            [48] = rtc_alarm_periodic_isr, /* RTC PERIOD (Periodic interrupt) */
            [49] = rtc_carry_isr, /* RTC CARRY (Carry interrupt) */
            [50] = agt_int_isr, /* AGT0 INT (AGT interrupt) */
            [51] = agt_int_isr, /* AGT1 INT (AGT interrupt) */
            [52] = r_icu_isr, /* ICU IRQ0 (External pin interrupt 0) */
            [53] = r_icu_isr, /* ICU IRQ1 (External pin interrupt 1) */
            [54] = r_icu_isr, /* ICU IRQ2 (External pin interrupt 2) */
            [55] = r_icu_isr, /* ICU IRQ3 (External pin interrupt 3) */
            [56] = r_icu_isr, /* ICU IRQ4 (External pin interrupt 4) */
            [57] = r_icu_isr, /* ICU IRQ5 (External pin interrupt 5) */
            [58] = r_icu_isr, /* ICU IRQ6 (External pin interrupt 6) */
            [59] = r_icu_isr, /* ICU IRQ7 (External pin interrupt 7) */
            [60] = r_icu_isr, /* ICU IRQ8 (External pin interrupt 8) */
            [61] = r_icu_isr, /* ICU IRQ9 (External pin interrupt 9) */
            [62] = r_icu_isr, /* ICU IRQ10 (External pin interrupt 10) */
            [63] = r_icu_isr, /* ICU IRQ11 (External pin interrupt 11) */
            [64] = r_icu_isr, /* ICU IRQ12 (External pin interrupt 12) */
            [65] = r_icu_isr, /* ICU IRQ13 (External pin interrupt 13) */
            [66] = r_icu_isr, /* ICU IRQ14 (External pin interrupt 14) */
            [67] = r_icu_isr, /* ICU IRQ15 (External pin interrupt 15) */
            [68] = iic_master_rxi_isr, /* IIC0 RXI (Receive data full) */
            [69] = iic_master_txi_isr, /* IIC0 TXI (Transmit data empty) */
            [70] = iic_master_tei_isr, /* IIC0 TEI (Transmit end) */
            [71] = iic_master_eri_isr, /* IIC0 ERI (Transfer error) */
            [72] = iic_master_rxi_isr, /* IIC1 RXI (Receive data full) */
            [73] = iic_master_txi_isr, /* IIC1 TXI (Transmit data empty) */
            [74] = iic_master_tei_isr, /* IIC1 TEI (Transmit end) */
            [75] = iic_master_eri_isr, /* IIC1 ERI (Transfer error) */
            [76] = iic_master_rxi_isr, /* IIC2 RXI (Receive data full) */
            [77] = iic_master_txi_isr, /* IIC2 TXI (Transmit data empty) */
            [78] = iic_master_tei_isr, /* IIC2 TEI (Transmit end) */
            [79] = iic_master_eri_isr, /* IIC2 ERI (Transfer error) */
        };
        const bsp_interrupt_event_t g_interrupt_event_link_select[BSP_ICU_VECTOR_MAX_ENTRIES] =
        {
            [0] = BSP_PRV_IELS_ENUM(EVENT_SPI0_RXI), /* SPI0 RXI (Receive buffer full) */
            [1] = BSP_PRV_IELS_ENUM(EVENT_SPI0_TXI), /* SPI0 TXI (Transmit buffer empty) */
            [2] = BSP_PRV_IELS_ENUM(EVENT_SPI0_TEI), /* SPI0 TEI (Transmission complete event) */
            [3] = BSP_PRV_IELS_ENUM(EVENT_SPI0_ERI), /* SPI0 ERI (Error) */
            [4] = BSP_PRV_IELS_ENUM(EVENT_SPI1_RXI), /* SPI1 RXI (Receive buffer full) */
            [5] = BSP_PRV_IELS_ENUM(EVENT_SPI1_TXI), /* SPI1 TXI (Transmit buffer empty) */
            [6] = BSP_PRV_IELS_ENUM(EVENT_SPI1_TEI), /* SPI1 TEI (Transmission complete event) */
            [7] = BSP_PRV_IELS_ENUM(EVENT_SPI1_ERI), /* SPI1 ERI (Error) */
            [8] = BSP_PRV_IELS_ENUM(EVENT_SCI0_RXI), /* SCI0 RXI (Receive data full) */
            [9] = BSP_PRV_IELS_ENUM(EVENT_SCI0_TXI), /* SCI0 TXI (Transmit data empty) */
            [10] = BSP_PRV_IELS_ENUM(EVENT_SCI0_TEI), /* SCI0 TEI (Transmit end) */
            [11] = BSP_PRV_IELS_ENUM(EVENT_SCI0_ERI), /* SCI0 ERI (Receive error) */
            [12] = BSP_PRV_IELS_ENUM(EVENT_SCI1_RXI), /* SCI1 RXI (Received data full) */
            [13] = BSP_PRV_IELS_ENUM(EVENT_SCI1_TXI), /* SCI1 TXI (Transmit data empty) */
            [14] = BSP_PRV_IELS_ENUM(EVENT_SCI1_TEI), /* SCI1 TEI (Transmit end) */
            [15] = BSP_PRV_IELS_ENUM(EVENT_SCI1_ERI), /* SCI1 ERI (Receive error) */
            [16] = BSP_PRV_IELS_ENUM(EVENT_SCI2_RXI), /* SCI2 RXI (Received data full) */
            [17] = BSP_PRV_IELS_ENUM(EVENT_SCI2_TXI), /* SCI2 TXI (Transmit data empty) */
            [18] = BSP_PRV_IELS_ENUM(EVENT_SCI2_TEI), /* SCI2 TEI (Transmit end) */
            [19] = BSP_PRV_IELS_ENUM(EVENT_SCI2_ERI), /* SCI2 ERI (Receive error) */
            [20] = BSP_PRV_IELS_ENUM(EVENT_SCI3_RXI), /* SCI3 RXI (Received data full) */
            [21] = BSP_PRV_IELS_ENUM(EVENT_SCI3_TXI), /* SCI3 TXI (Transmit data empty) */
            [22] = BSP_PRV_IELS_ENUM(EVENT_SCI3_TEI), /* SCI3 TEI (Transmit end) */
            [23] = BSP_PRV_IELS_ENUM(EVENT_SCI3_ERI), /* SCI3 ERI (Receive error) */
            [24] = BSP_PRV_IELS_ENUM(EVENT_SCI4_RXI), /* SCI4 RXI (Received data full) */
            [25] = BSP_PRV_IELS_ENUM(EVENT_SCI4_TXI), /* SCI4 TXI (Transmit data empty) */
            [26] = BSP_PRV_IELS_ENUM(EVENT_SCI4_TEI), /* SCI4 TEI (Transmit end) */
            [27] = BSP_PRV_IELS_ENUM(EVENT_SCI4_ERI), /* SCI4 ERI (Receive error) */
            [28] = BSP_PRV_IELS_ENUM(EVENT_SCI5_RXI), /* SCI5 RXI (Received data full) */
            [29] = BSP_PRV_IELS_ENUM(EVENT_SCI5_TXI), /* SCI5 TXI (Transmit data empty) */
            [30] = BSP_PRV_IELS_ENUM(EVENT_SCI5_TEI), /* SCI5 TEI (Transmit end) */
            [31] = BSP_PRV_IELS_ENUM(EVENT_SCI5_ERI), /* SCI5 ERI (Receive error) */
            [32] = BSP_PRV_IELS_ENUM(EVENT_SCI6_RXI), /* SCI6 RXI (Received data full) */
            [33] = BSP_PRV_IELS_ENUM(EVENT_SCI6_TXI), /* SCI6 TXI (Transmit data empty) */
            [34] = BSP_PRV_IELS_ENUM(EVENT_SCI6_TEI), /* SCI6 TEI (Transmit end) */
            [35] = BSP_PRV_IELS_ENUM(EVENT_SCI6_ERI), /* SCI6 ERI (Receive error) */
            [36] = BSP_PRV_IELS_ENUM(EVENT_SCI7_RXI), /* SCI7 RXI (Received data full) */
            [37] = BSP_PRV_IELS_ENUM(EVENT_SCI7_TXI), /* SCI7 TXI (Transmit data empty) */
            [38] = BSP_PRV_IELS_ENUM(EVENT_SCI7_TEI), /* SCI7 TEI (Transmit end) */
            [39] = BSP_PRV_IELS_ENUM(EVENT_SCI7_ERI), /* SCI7 ERI (Receive error) */
            [40] = BSP_PRV_IELS_ENUM(EVENT_SCI8_RXI), /* SCI8 RXI (Received data full) */
            [41] = BSP_PRV_IELS_ENUM(EVENT_SCI8_TXI), /* SCI8 TXI (Transmit data empty) */
            [42] = BSP_PRV_IELS_ENUM(EVENT_SCI8_TEI), /* SCI8 TEI (Transmit end) */
            [43] = BSP_PRV_IELS_ENUM(EVENT_SCI8_ERI), /* SCI8 ERI (Receive error) */
            [44] = BSP_PRV_IELS_ENUM(EVENT_SCI9_RXI), /* SCI9 RXI (Received data full) */
            [45] = BSP_PRV_IELS_ENUM(EVENT_SCI9_TXI), /* SCI9 TXI (Transmit data empty) */
            [46] = BSP_PRV_IELS_ENUM(EVENT_SCI9_TEI), /* SCI9 TEI (Transmit end) */
            [47] = BSP_PRV_IELS_ENUM(EVENT_SCI9_ERI), /* SCI9 ERI (Receive error) */
            [48] = BSP_PRV_IELS_ENUM(EVENT_RTC_PERIOD), /* RTC PERIOD (Periodic interrupt) */
            [49] = BSP_PRV_IELS_ENUM(EVENT_RTC_CARRY), /* RTC CARRY (Carry interrupt) */
            [50] = BSP_PRV_IELS_ENUM(EVENT_AGT0_INT), /* AGT0 INT (AGT interrupt) */
            [51] = BSP_PRV_IELS_ENUM(EVENT_AGT1_INT), /* AGT1 INT (AGT interrupt) */
            [52] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ0), /* ICU IRQ0 (External pin interrupt 0) */
            [53] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ1), /* ICU IRQ1 (External pin interrupt 1) */
            [54] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ2), /* ICU IRQ2 (External pin interrupt 2) */
            [55] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ3), /* ICU IRQ3 (External pin interrupt 3) */
            [56] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ4), /* ICU IRQ4 (External pin interrupt 4) */
            [57] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ5), /* ICU IRQ5 (External pin interrupt 5) */
            [58] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ6), /* ICU IRQ6 (External pin interrupt 6) */
            [59] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ7), /* ICU IRQ7 (External pin interrupt 7) */
            [60] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ8), /* ICU IRQ8 (External pin interrupt 8) */
            [61] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ9), /* ICU IRQ9 (External pin interrupt 9) */
            [62] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ10), /* ICU IRQ10 (External pin interrupt 10) */
            [63] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ11), /* ICU IRQ11 (External pin interrupt 11) */
            [64] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ12), /* ICU IRQ12 (External pin interrupt 12) */
            [65] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ13), /* ICU IRQ13 (External pin interrupt 13) */
            [66] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ14), /* ICU IRQ14 (External pin interrupt 14) */
            [67] = BSP_PRV_IELS_ENUM(EVENT_ICU_IRQ15), /* ICU IRQ15 (External pin interrupt 15) */
            [68] = BSP_PRV_IELS_ENUM(EVENT_IIC0_RXI), /* IIC0 RXI (Receive data full) */
            [69] = BSP_PRV_IELS_ENUM(EVENT_IIC0_TXI), /* IIC0 TXI (Transmit data empty) */
            [70] = BSP_PRV_IELS_ENUM(EVENT_IIC0_TEI), /* IIC0 TEI (Transmit end) */
            [71] = BSP_PRV_IELS_ENUM(EVENT_IIC0_ERI), /* IIC0 ERI (Transfer error) */
            [72] = BSP_PRV_IELS_ENUM(EVENT_IIC1_RXI), /* IIC1 RXI (Receive data full) */
            [73] = BSP_PRV_IELS_ENUM(EVENT_IIC1_TXI), /* IIC1 TXI (Transmit data empty) */
            [74] = BSP_PRV_IELS_ENUM(EVENT_IIC1_TEI), /* IIC1 TEI (Transmit end) */
            [75] = BSP_PRV_IELS_ENUM(EVENT_IIC1_ERI), /* IIC1 ERI (Transfer error) */
            [76] = BSP_PRV_IELS_ENUM(EVENT_IIC2_RXI), /* IIC2 RXI (Receive data full) */
            [77] = BSP_PRV_IELS_ENUM(EVENT_IIC2_TXI), /* IIC2 TXI (Transmit data empty) */
            [78] = BSP_PRV_IELS_ENUM(EVENT_IIC2_TEI), /* IIC2 TEI (Transmit end) */
            [79] = BSP_PRV_IELS_ENUM(EVENT_IIC2_ERI), /* IIC2 ERI (Transfer error) */
        };
        #endif
