#include <stdio.h>
#include <stdbool.h>
#include "hal_data.h"
#if defined(USE_SEGGER_RTT)
#include "SEGGER_RTT.h"

volatile int _Cnt;
volatile int _Delay;
#endif

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

#if 0
volatile bool uart_recv_flag = false;
volatile bool uart_send_complete_flag = false;

/* Callback function */
void user_uart_callback(uart_callback_args_t *p_args)
{
    /* TODO: add your own code here */
    if (p_args->event == UART_EVENT_RX_COMPLETE) {
        uart_recv_flag = true;
    } else if (p_args->event == UART_EVENT_TX_COMPLETE) {
        uart_send_complete_flag = true;
    }
}

void ra4m_sci_init() {
    fsp_err_t status = FSP_SUCCESS;
    status = R_SCI_UART_Open(&g_uart0_ctrl, &g_uart0_cfg);
    if (FSP_SUCCESS != status) {
        __BKPT();
    }
}

uint8_t ra4m_sci_rx() {
    uint8_t c;
    fsp_err_t status = FSP_SUCCESS;
    status = R_SCI_UART_Read(&g_uart0_ctrl, &c, 1);
    if (FSP_SUCCESS != status) {
        __BKPT();
    }
    while (!uart_recv_flag) {}
    uart_recv_flag = false;
    return c;
}

void ra4m_sci_tx(uint8_t c) {
    fsp_err_t status = FSP_SUCCESS;
    status = R_SCI_UART_Write(&g_uart0_ctrl, &c, 1);
    if (FSP_SUCCESS != status) {
        __BKPT();
    }
    while (!uart_send_complete_flag) {}
    uart_send_complete_flag = false;
}
#endif

void ra_main(uint32_t reset_mode);

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {
	/* TODO: add your own code here */

#if defined(USE_SEGGER_RTT)
    SEGGER_RTT_WriteString(0, "SEGGER Real-Time-Terminal\r\n");
    SEGGER_RTT_ConfigUpBuffer(0, NULL, NULL, 0, SEGGER_RTT_MODE_NO_BLOCK_SKIP);
#endif
    ra_main(0);
#if 0
    while (true) {
    	c = ra4m_sci_rx();
        if (c == 0x03) {
            break;
        }
        ra4m_sci_tx(c);
    }
    status = R_SCI_UART_Close(&g_uart0_ctrl);
    if (FSP_SUCCESS != status) {
        __BKPT();
    }
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event) {
	if (BSP_WARM_START_RESET == event) {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
	}

	if (BSP_WARM_START_POST_C == event) {
		/* C runtime environment and system clocks are setup. */

		/* Configure pins. */
		R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
	}
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
